github: [metadata]
encoding: UTF-8
kramdown:
    input: GFM
    hard_wrap: false
    toc_levels: 1..3
future: true
jailed: false
theme: jekyll-theme-cayman
gfm_quirks: paragraph_end
keep_files: ["docs"]
exclude: ["docs"]
